title: Srikar Reddy Karemma # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Highly skilled software engineer with experience in developing scalable, high-performance platforms, specializing in Identity and Access Management (IAM), RESTful APIs, and cloud-native solutions. Proficient in Java, JavaScript, and modern frameworks including SpringBoot, Angular, and Kubernetes, with a deep insight of network protocols, security frameworks, JVM internals and failure detection algorithms. Expertise in building and optimizing mission-critical systems at industry-leading organizations such as Walmart, NASA, and Tech Mahindra. Experienced in full-stack development, blockchain technologies, and designing advanced self-optimizing algorithms. Committed to driving innovation through robust architecture, efficient cloud deployments, and secure application development.
  <br><br>
  <a href="https://www.linkedin.com/in/srikarreddykaremma/">LinkedIn Profile</a> 
 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
