title: Srikar Reddy Karemma # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  ** Experienced Full-stack Developer with practical knowledge in technologies like Hyperledger Fabric, Ethereum and Corda R3. Skilled in developing end-to-end MEAN and MERN stack applications. Strong engineering professional pursuing Masters in Computer Science from George Mason University **. 
  <br><br>
  <a href="https://www.linkedin.com/in/srikarreddykaremma/">LinkedIn Profile</a> 
  ** Job Experience :**
  Graduate Teaching Assistant at George Mason University: 
  I  currently work as a Graduate Teaching Assistant in the Department of Information Sciences and Technology, assisting more than 100 students with a Python-based advanced course.
  
  Graduate Research Assistant at George Mason University :
  I worked as a Graduate Research Assistant involved with The Helio-physics Application Programmer’s Interface (HAPI). It is a data access specification (Backed by NASA), which uses a RESTful API and streaming format specification for delivering time series data.
  
  Full Stack Developer at Tech Mahindra :
  I was involved in building full-stack applications using MEAN and MERN stacks on top of blockchain technologies like Ethereum and Hyperledger Fabric.
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
